AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Sample SAM Template for cf-oac-demo #magic___^_^___line

Mappings:
  Constants:
    ManagedPolicyIds:
      CachingDisabled: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
      AllViewer: 216adef6-5c7f-47e4-b989-5492eafa07d3

Resources:
  StreamingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Timeout: 10
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: RESPONSE_STREAM
  LambdaResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref StreamingFunction
      FunctionUrlAuthType: AWS_IAM
      Principal: cloudfront.amazonaws.com
      SourceArn: !Join
      - ''
      - - 'arn:aws:cloudfront::'
        - !Ref AWS::AccountId
        - ':distribution/'
        - !Ref CloudfrontDistribution
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: An optional description for the origin access control
        Name: LambdFunctionURLOAC
        OriginAccessControlOriginType: lambda
        SigningBehavior: always
        SigningProtocol: sigv4
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        IPV6Enabled: true
        HttpVersion: http2
        Origins:
        - Id: MyOrigin
          OriginAccessControlId: !Ref CloudFrontOAC
          DomainName: !Select
          - 2
          - !Split
            - /
            - !GetAtt StreamingFunctionUrl.FunctionUrl
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
            - TLSv1.2
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: MyOrigin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !FindInMap [Constants, ManagedPolicyIds, CachingDisabled]

Outputs:
  StreamingFunction:
    Description: Streaming Lambda Function ARN
    Value: !GetAtt StreamingFunction.Arn
  StreamingFunctionURL:
    Description: Streaming Lambda Function URL
    Value: !GetAtt StreamingFunctionUrl.FunctionUrl
  DistributionDomainName:
    Description: Distribution domain name
    Value: !GetAtt CloudfrontDistribution.DomainName
    Export:
      Name: DistributionDomainName
  DistributionId:
    Description: Distribution ID
    Value: !GetAtt CloudfrontDistribution.Id
  DistributionArn:
    Description: Distribution ARN
    Export:
      Name: DistributionArn
    Value: !Join
    - ''
    - - 'arn:aws:cloudfront::'
      - !Ref AWS::AccountId
      - ':distribution/'
      - !Ref CloudfrontDistribution
